# Generated by Django 5.1.3 on 2024-11-21 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(max_length=255)),
                ("balance", models.DecimalField(decimal_places=18, default=0, max_digits=36)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("txid", models.CharField(max_length=255, unique=True)),
                ("amount", models.DecimalField(decimal_places=18, max_digits=36)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="transactions", to="core.wallet"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["txid"], name="core_transa_txid_d6d93a_idx"),
                    models.Index(fields=["wallet"], name="core_transa_wallet__9c10a1_idx"),
                ],
            },
        ),
    ]
